### PR TITLE
fix: Prevent ADMIN roles to be changed to non-ADMIN roles

### LINKED ISSUE #202: Blocking ADMINs from changing other ADMIN or themselves roles
**Describe the bug**
Admin can change roles for other people. But currently, they can also change their own roles. If an Admin changes his/her role to another role, the admin will be locked out of the app, with the screen showing “access denied”. The user cannot undo the change easily.

**Expected behavior**
Don’t allow admins to change the role of other admins through the UI.

### PR DESCRIPTION
**Pull request by Qianru69**
Co-authored-by: Shawn Templer <stemp001@ucr.edu>
Co-authored-by: Vanessa Valle <vallevanessa13@gmail.com>

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #202

### CODE REVIEW

File: pages/api/modifyuser.js [hunk 1]
```diff
@@ -47,6 +61,21 @@ export default async function handle(req, res) {
...
+      where: {
+        id: body.id
+      },
+      data: {
+        name: body.name,
+        email: body.email
+      }
+    });
+    //202 return indicates the request is accepted, but not entirely completed.
+    return res.status(202).end();
```
Comment (roberthuskins) [inline pages/api/modifyuser.js:77]: My opinion is we should just block the request if it's bad. Especially since this response has no body explaining what parts of the request did/didn't went though.

Comment (Qianru69) [reply pages/api/modifyuser.js:77]: This version allows users to make changes to the name and email, but not the role if the role is changing from Admin to non-Admin. Do you suggest blocking all changes whenever a user is modifying an ADMIN's role? If so, in the next PR, shall we also make a pop-up message to explain why this request is denied? (Ex: DO NOT MODIFY ADMIN'S ROLE)

Comment (roberthuskins) [reply pages/api/modifyuser.js:77]: In general you should always block bad requests so callers know to stop making them. Also, we return a 202 without giving any response body, if we send this then callers will not know what actually got processed and what didn't.

I suggest we block the request from the API side (this API is exposed to the public internet), and then on the UI we prevent any bad requests to be possible. Ideally roles will be a dropdown menu, and for a user that is an ADMIN we just don't let them change the role, don't even give them the option to.

Comment (Qianru69) [reply pages/api/modifyuser.js:77]: Got it! Thank you, Robert! We will edit the code in this pull request to completely block the bad requests, and return 403 (Forbidden) if it happens. And we will also try to edit the UI to ensure the users won't be able to submit bad requests.

**Review by roberthuskins — APPROVED** [review]
