### PR TITLE
fix: Add authentication to APIs

### LINKED ISSUE #116: Authenticate all API endpoints
Most of the API endpoints are not secure.  We should add checks to ensure that only authorized users have access to specific endpoints.  Take a look at this [file](https://github.com/freeCodeCamp/classroom/pull/117/files#diff-5d89fa49bedc90b694bb6d0d632d3622b6ca948548cfd3cd4cb901815138660e)

### PR DESCRIPTION
**Pull request by St3phy831**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #116

### CODE REVIEW

File: pages/api/create_class_teacher.js [hunk 1]
```diff
@@ -1,6 +1,33 @@
...
+    res.status(405).end();
+  }
+
+  if (!session) {
+    res.status(403).end();
+  }
+
+  let users = await prisma.user.findMany({
+    where: {
+      role: 'TEACHER'
```
Comment (roberthuskins) [inline pages/api/create_class_teacher.js:19]: check if prisma lets you put array for ['TEACHER', 'ADMIN'] here

File: pages/api/deleteclass.js [hunk 2]
```diff
@@ -1,6 +1,32 @@
...
+    res.status(405).end();
+  }
+
+  if (!session) {
+    res.status(403).end();
+  }
+
+  let users = await prisma.user.findMany({
+    where: {
+      role: 'TEACHER'
```
Comment (roberthuskins) [inline pages/api/deleteclass.js:19]: same here

File: pages/api/student_email_join.js [hunk 3]
```diff
@@ -1,7 +1,26 @@
...
+  }
+
   const data = JSON.parse(req.body);
+
+  //make sure user is adding themselves to a classroom
+  if (session.user.email !== data['email']) {
+    res.status(403).end();
+  }
+
   const userInfoReq = await fetch(
```
Comment (roberthuskins) [inline pages/api/student_email_join.js:24]: I think we should pull for the database here instead of querying our own API

File: pages/api/create_class_teacher.js [hunk 4]
```diff
@@ -1,6 +1,33 @@
...
+
+  if (!req.method == 'POST') {
+    res.status(405).end();
+  }
+
+  if (!session) {
+    res.status(403).end();
+  }
+
+  let users = await prisma.user.findMany({
```
Comment (St3phy831) [inline pages/api/create_class_teacher.js:17]: Use findUnique

Comment (roberthuskins) [inline pages/api/create_class_teacher.js:17]: See if possible to findunique based on user email, and then check the role of that unique instead.

This code gets a list of ALL teachers, then sees if user is in that list.

Instead, we should get user's data based on findunique(user email), then check if the data we get back has the right role.

This needs to be changed for all endpoints. My bad.

File: pages/api/create_class_teacher.js (hunk 1 above)
Comment (St3phy831) [reply pages/api/create_class_teacher.js]: Didn't need anymore. Went a new route by using findUnique query

File: pages/api/student_email_join.js [hunk 5]
```diff
@@ -1,37 +1,51 @@
...
-      });
+
+  //make sure user is adding themselves to a classroom
+  if (user.email !== data['email']) {
+    res.status(403).end();
+  }
+
+  const existingStudent = await prisma.classroom.findUniqueOrThrow({
+    where: {
+      classroomId: data['classId'][0]
```
Comment (St3phy831) [inline pages/api/student_email_join.js:32]: Why are we indexing 0? Is data['classId'] an array of classIds?

File: pages/api/create_class_teacher.js [hunk 6]
```diff
@@ -1,8 +1,37 @@
...
+
+  if (!req.method == 'POST') {
+    res.status(405).end();
+  }
+
+  if (!session) {
+    res.status(403).end();
+  }
+
+  let user = await prisma.user.findUniqueOrThrow({
```
Comment (St3phy831) [inline pages/api/create_class_teacher.js:17]: Decided to use findUniqueOrThrow for queries instead of findUnique because it throws an error if the record is not found.

File: pages/api/student_email_join.js [hunk 7]
```diff
@@ -1,37 +1,51 @@
...
+
+  if (!req.method == 'POST') {
+    res.status(405).end();
+  }
+
+  if (!session) {
+    res.status(403).end();
+  }
+
+  let user = await prisma.user.findUniqueOrThrow({
```
Comment (St3phy831) [inline pages/api/student_email_join.js:17]: Is this what you meant by pulling from databse instead of querying API? @roberthuskins

File: pages/api/student_email_join.js (hunk 5 above)
Comment (roberthuskins) [reply pages/api/student_email_join.js:32]: Good question, I didn't design this API. I'll ask @egall18 saturday

**Review by roberthuskins — COMMENTED** [review]
LGTM

**Comment by raisedadead** [comment]
@freeCodeCamp/classroom, you need to click the "green approve" button for the PR to be eligible for a merge.

**Review by GuillermoFloresV — APPROVED** [review]

**Comment by GuillermoFloresV** [comment]
LGTM, thanks, Stephanie!!
