### PR TITLE
fix: refactored data processing into its own file

### LINKED ISSUE #328: Create seperate data processing function for class dashboard
In order to eliminate the need to load the whole dashboard page to test components inside of it, we need to have the [data processing](https://github.com/freeCodeCamp/classroom/blob/main/components/dashtable_v2.js#L6-L97) that happens inside of the dashboard be a function (preferably in a new file) that we can simply import. This will help break down the code into more testable components.

The flow should look something like this:

1. Create a new file where our data processing code will live
2. Copy and paste the lines mentioned above from our dashboard page into this new file we created on step 1
3. Make sure the function is exported in the new file (so we can use it in our dashboard & tests)
4. Refactor the dashboard code to use the new function rather than code directly written inside of the dashboard page.

### PR DESCRIPTION
**Pull request by theGaryLarson**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #328 

I am a member of CodeDay and this is my first contribution. I believe I followed the guidelines closely but didn't see a good label for scope in PR title so left it blank.

I refactored the dashBoard data processing into its own file in /util and then imported it into dashtable_v2.js

Co-authored-by: Komal Kaur <Kaur91499@gmail.com>

### CODE REVIEW

**Comment by GuillermoFloresV** [comment]
Hi Gary, 

Thanks for your PR! We have seen this and are working to be able to review all of our new PRs, but typically this is done by hand (pulling your changes onto my dev environment and testing for myself) so this can take a while with so many PRs.

However, I'll be reviewing this PR on Monday (07/09/23), just wanted to give you a heads-up that we have seen it.

Thanks for your contribution and patience!

**Comment by theGaryLarson** [comment]
@GuillermoFloresV I was able to figure out how to write tests. It is a pretty simple one but wanted to follow best practices. In the docs it says to put component tests next to their components but not sure if my test should go in the __tests__ dir or in the same file as my method in ./util/processDashBoardData.js.

Once I can get confirmation I'll add the test by pushing to this branch

File: components/dashtable_v2.js [hunk 1]
```diff
@@ -1,133 +1,13 @@
+// components/dashtable_v2.js
 import { useTable } from 'react-table';
-import React from 'react';
-import getStudentActivity from './studentActivity';
+import React, { useMemo } from 'react';
+import { processDashboardData } from '../util/processDashboardData';
```
Comment (GuillermoFloresV) [inline components/dashtable_v2.js:4]: This module cannot be found when running the application. See below.
image

It looks like you did not import it correctly, your function exists inside of `'../util/processDashBoardData';` not `../util/processDashboardData';`

Please rename your `util/processDashBoardData.js` file to `util/processDashboardData.js` so that the module can be correctly imported.

File: util/processDashBoardData.test.js [hunk 2]
```diff
@@ -0,0 +1,98 @@
+import { processDashboardData } from './processDashBoardData';
```
Comment (GuillermoFloresV) [inline util/processDashBoardData.test.js:1]: Rename this import to fit the new name of your file (`util/processDashboardData.js`) Otherwise, the test will not pass.

File: util/processDashBoardData.test.js
Comment (GuillermoFloresV) [inline util/processDashBoardData.test.js:1]: Rename this test to `processDashboardData.test.js` To keep it consistent with your other file

**Review by GuillermoFloresV — CHANGES_REQUESTED** [review]

**Comment by GuillermoFloresV** [comment]
> @GuillermoFloresV I was able to figure out how to write tests. It is a pretty simple one but wanted to follow best practices. In the docs it says to put component tests next to their components but not sure if my test should go in the **tests** dir or in the same file as my method in ./util/processDashBoardData.js.
> 
> Once I can get confirmation I'll add the test by pushing to this branch

Hi Gary, I've left some comments on your code. Regarding your question, we could move the testing file over to the `__test__` folder. Please create a sub-folder named `__util__` inside of `__test__` and paste your test in there, while there is no set naming/folder structure convention, we are currently using a convention where all our tests live inside of the `__test__` folder. Thanks!

File: components/dashtable_v2.js (hunk 1 above)
Comment (theGaryLarson) [reply components/dashtable_v2.js:4]: Crap... Sorry about that. Fixed!

File: util/processDashBoardData.test.js (hunk 2 above)
Comment (theGaryLarson) [reply util/processDashBoardData.test.js]: fixed

File: util/processDashBoardData.test.js
Comment (theGaryLarson) [reply util/processDashBoardData.test.js:1]: fixed

**Comment by theGaryLarson** [comment]
Hi @GuillermoFloresV I work as well have to frontload the beginning of my week with my CodeDay hours. I just got this merge conflict resolved and I believe its good to go.

**Review by GuillermoFloresV — APPROVED** [review]
