### PR TITLE
fix: Join code refactored for students

### LINKED ISSUE #114: Create a Join-class button component on the Join page which assigns a role of "student" to the user
Workflow: 

1. User clicks on join link
2. User lands on the Join page
3. User clicks on the "Join" button 
4. User is assigned a role of "student" 
5. User is added to the correct classroom (based on the ID in the join url)

### PR DESCRIPTION
**Pull request by GuillermoFloresV**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #114, #115 

At some point during our refactoring, students were unable to join classrooms. This PR fixes that alongside an already planned refactoring for this section of our codebase that used an old solution that required a separate mock server to be running.

### CODE REVIEW

**Comment by GuillermoFloresV** [comment]
@freeCodeCamp/classroom Hey everyone, were we still going to implement adding multiple teachers into a single classroom? if so I can add an else if statement to handle when teachers/admins attempt to join a classroom since currently the code simply converts them into a student

File: pages/api/student_email_join.js [hunk 1]
```diff
@@ -1,37 +1,59 @@
...
+
+  if (!req.method == 'PUT') {
+    res.status(405).end();
+  }
+
+  if (!session) {
+    res.status(403).end();
+  }
+
   const data = JSON.parse(req.body);
```
Comment (roberthuskins) [inline pages/api/student_email_join.js:17]: I think we decided earlier that form body should be JSON and we shouldn't need to parse JSON from plaintext going forward right?

Comment (GuillermoFloresV) [reply pages/api/student_email_join.js]: fixed.

**Review by EPeralta18 — APPROVED** [review]

File: pages/api/student_email_join.js [hunk 2]
```diff
@@ -1,37 +1,63 @@
...
+      fccUserIds: true
     }
-    const createdStudentEmail = await prisma.classroom.update({
+  });
+  const existsInClassroom = checkClass.fccUserIds.includes(userInfo.id);
+  if (existsInClassroom) {
+    res.status(409).end();
+  } else if (userInfo.role === 'TEACHER' || userInfo.role === 'ADMIN') {
+    // update the teachers to also include (not overwrite) this new teacher.
+    // some prisma query to add a new teacher to the list of teachers in that classroom.
```
Comment (utsab) [inline pages/api/student_email_join.js:41]: Having an empty if statement body here seems odd.  It looks like there is some additional logic you intend to add here in the future.  Can you file an issue for this additional logic and somehow remove the empty if statement for the time being?

File: pages/join/[...joinCode].js [hunk 3]
```diff
@@ -2,110 +2,110 @@ import Head from 'next/head';
...
+    try {
+      const res = await fetch(`/api/student_email_join`, {
+        method: 'PUT',
+        headers: {
+          'Content-Type': 'application/json'
+        },
+        body: JSON.stringify(formData)
+      });
+      if (res.status === 409) {
+        alert('You have already joined this classroom.');
```
Comment (utsab) [inline pages/join/[...joinCode].js:33]: It would be better to generate the error message on the server (in api/student_email_join) and then have the browser display any errors that the server sends over.  For now, it's ok to leave it as is, but I think we should file an issue to refactor the error message handling eventually.

**Review by utsab — APPROVED** [review]

File: pages/api/student_email_join.js (hunk 2 above)
Comment (GuillermoFloresV) [reply pages/api/student_email_join.js:41]: Sure thing. sorry this took a while for me to get back to, just pushed the change and will file an issue right now.
