### PR TITLE
fix page redirects across all pages

### LINKED ISSUE #497: Unauthorized access to the /classes page should show a more descriptive error message
**Describe the bug**
When an unauthorized user (not a "TEACHER") clicks on the "classes" link, the app redirects to a blank page.  

**To Reproduce**
1. Click "Sign in"
2. Sign in with Github 
3. The app will redirect you back to the homepage
4. On your terminal, run the command "npx prisma studio"
5. In Prisma Studio, open the "User" table.  Confirm that your user has a role of "NONE". 
6.  Back on the homepage of the Classroom app, click on "Classes".  The resulting page will be totally blank. 

**Expected behavior**
We should see a more descriptive error message that says "Access Denied".  The browser should redirect to the /error page. 

**Screenshots**
Current behavior (blank screen): 
Screen Shot 2023-10-19 at 8 40 46 PM

Expected behavior: 
Screen Shot 2023-10-19 at 8 40 25 PM

**Additional context**
I am using Github Codespaces (Linux) to reproduce this issue.

### PR DESCRIPTION
**Pull request by victoriavo256**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Co-authored by: Dylan Uribe  <dyluri007@gmail.com>
Co-authored by: Ann Pan <ypan413@gatech.edu>

Thank you to SenthilKumar Ilango <sen1517@gmail.com> for mentoring us.

Resolved Issue #497 and refactored all page redirects. Redirects were previously handled with ctx.writeHead, but we replaced it with our method called redirectUser which uses the recommended page redirect instruction provided by next.js. (https://nextjs.org/docs/pages/api-reference/functions/get-server-side-props#redirect) Tested changes locally.

Closes #497

### CODE REVIEW

**Review by senthil1288 — COMMENTED** [review]
Good Work!! Looks like you guys manually tested these changes, hope there was a UI test framework in place to test this.  Nevertheless, the code and documentation is pretty clean!!

File: util/redirectUser.js [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+const redirectUser = destination => {
+  return {
+    redirect: {
+      destination: destination,
+      permanent: false
+    }
+  };
+};
+
+export default redirectUser;
```
Comment (ngillux) [inline util/redirectUser.js:17]: Tested the PR by doing the following (all checks resulted as expected):

1. Initially signing in as user ‘NONE’ which is the default user when first signing on to the app -> this correctly showed the ‘Access Denied’ UI as intended
Screenshot 2024-02-10 at 6 33 54 PM

2. Initially signing in as user ‘STUDENT’ -> this correctly showed the ‘Access Denied’ UI as intended
Screenshot 2024-02-10 at 6 33 54 PM



3. Initially signing in as user ‘TEACHER’ -> this correctly shows the class creation UI as intended
Screenshot 2024-02-10 at 6 33 02 PM

4. Initially signing in as user ‘ADMIN’ -> this correctly displays the admin dashboard
Screenshot 2024-02-10 at 6 38 55 PM

Edge case to consider:
When updating the user privileges in Prisma, the UI does not update immediately as the link is still set to [https://{CODESPACES}.app.github.dev/error](about:blank). This could mean that logic may need to be added which would update the URL (‘error’, ‘admin’, ‘teacher’, ‘student’) once a user privilege is updated.

Mentioning @utsab for further view.

**Review by utsab — APPROVED** [review]
The pull request looks good.  I appreciate that you not only fixed the original problem but also applied the new redirect logic throughout the app.  

It would have been nice to see a few more unit tests to confirm that the page actually displays the error message (similar to what @ngillux tested for manually) as well as for the other pages you modified, but we can open separate issues for that.  

Thank you for your contribution!
